name: chat_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.0
  go_router: ^14.2.0
  cloud_firestore: ^5.0.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/

analyzer:
  plugins:
    - custom_lint

flutter_gen:
  output: lib/core/gen/
  line_length: 80

